### ISSUE TITLE
Provider confirmation policy

### ISSUE THREAD

**Issue by jkbquabeck** [sovity/edc-extensions#859] opened 2024-03-26 10:45 UTC
# Feature Request

## Description

_A clear and concise description of what the customer wants to happen._

-   As a USER who PRECONDITIONS, I want to DO_THING, so I can ACCOMPLISH_GOAL.

## Which Areas Would Be Affected?

_e.g., DPF, CI, build, transfer, etc._

## Why Is the Feature Desired?

_What problems does that user face that existing functionalities do solve?_

## How does this tie into the current product?

_Describe whether this request is related to an existing workflow, feature, or otherwise something in the product today. Or, does this open us up to new innovative ideas?_

## (For sovity Team to complete) Stakeholders

_Add more on who asked for this, i.e. company, person, how much they pay us, what their tier is, are they a strategic account, etc. Who needs to be kept up-to-date about this feature?_

## (For sovity Team to complete) Solution Proposal and Work Breakdown

```[tasklist]
- [ ] Fix the GitHub Projects Labels, Sprint and other Metadata
- [ ] Refine further action items for this feature request
```
---------------MDS format for quick inspection-------------
https://github.com/Mobility-Data-Space/MDS-Project/issues/60

# Background  

## Problem statement
Currently the provider has possibility to restrict consumers, but just before he defined the offer. 

## Customer perspective
It would be much more efficient to turn the tables and give the provider a possibility to decide whether he wants to provide data for a certain consumer or not in realtime (on request). 

## Business value
This policy can increase the flexibility of the data space anf offers more business opportunities for participants. 

# Proposed solution

## Description of the feature
New policy "Provider confirmation" shall be implemented. If the provider selects this policy, the consumer sents the offer request, which can be accepted or declined by provider. In first case the contract is signed. In both cases the consumer shall be informed about the provider's decision.

## Dependencies 
- Broker needs to be adjusted to display necessary manual interaction
- This feature can be downprioritized if the editing of connector restricted policy will be implemented. Both features do not completely replace each other, but to a certain extent.

## Suggested visual realization
As Policy. The consumer shall have a possibility to send a request via both UI and API. The provider shall have a possibility to accept or decline the request via both UI and API. The consumer shall be informed about desicion of the provider via UI. 

# Challenges

- From [here](https://github.com/sovity/edc-extensions/issues/605#issuecomment-1970648890)
- Usage via Management API/Wrapper: DSP negotiation must be intercepted and triggerable for certain steps.
- Enhance documentation about API and manual negotiation steps (for systems)
- Assets need another flag to distinguish assets with and without such a policy (maybe identification via policy would be enough)
-  What about cancel a negotiation request?
-  A negotiation request might need to be deleted after x weeks
- Shall a potential consumer be able to ask or notify the provider again?
- How to notify consumer, once a contract was agreed on provider side?

# User stories
As Provider I want to have a possibility to decide whether I accept or decline the certain consumer aftre his request for may offer. 

As consumer I want to be informed immediately after the provider's desicion whether my request was accepted or declined.

# Outlook
TBD

**Comment by SebastianOpriel** [comment] 2024-04-04 10:49
duplicate of https://github.com/sovity/edc-extensions/issues/605

**Closed by SebastianOpriel** 2024-04-04 10:49 UTC
Labels: kind/enhancement, scope/ce, task/analyze, scope/mds, status/blocked/needs-product
