### ISSUE TITLE
Error Registering a Resource at Broker UI

### ISSUE THREAD

**Issue by bv5317** [sovity/edc-extensions#87] opened 2023-02-03 09:50 UTC
# Bug Report

## Description

Facing an error while running the docker compose, the dataspace connector status is shown as ready however, 
while trying to register the resource at broker, it says ""**Failed to obtain token: {"error":"invalid_client","error_description":"Client unknown"}**""

Using this as Client_id with the given SKI:AKI values which was generated from the get_client.sh script "**AE:92:8C:65:A3:FB:41:F1:05:3E:EF:19:05:84:DA:6B:E2:25:E6:90:55:8C:E0:EE:C9:79:10:F5:DD:1E:BF:33:87:8B:8A:BE:A4:01:16:64**" 

Apparently, in the readme file it says the client_id has "**keyid**" in between the SKI:AKI combinations but it did not generated any **keyid** in this case. Wondering if the client_sh script needs to get updated.

**Comment by tmberthold** [comment] 2023-02-03 09:52
In a way a duplicate of:
https://github.com/sovity/edc-extensions/issues/86

We're going to take a look at that.

**Comment by tmberthold** [comment] 2023-02-06 07:17
Will close this one in favor of #86 as a duplicate.

**Closed by tmberthold** 2023-02-06 07:17 UTC
Labels: bug
