### ISSUE TITLE
EDC Connector Configuration and Contract Negotiation

### ISSUE THREAD

**Issue by dcarmen1** [sovity/edc-extensions#379] opened 2023-06-13 11:04 UTC
# Feature Request

Request for Assistance with Connector Configuration and Contract Negotiation

## Description

After completing all the necessary configurations for the connector, including the corresponding certificates and exposing the external endpoints (11001, 11002, 11003, 11004) on our cloud platform to ensure internet accessibility, we received confirmation that the connector is up and running.

However, when attempting to research the connector from the MDS catalog on the PRO environment, we encountered a problem. We were able to retrieve all the resources from a specific external connector, but when trying to create a contract, the process enters a loop and the status remains stuck at "REQUESTED" instead of transitioning to "COMPLETED". Consequently, no contract is generated.

Would appreciate guidance on any additional configurations or settings that need to be considered to address this issue. It is important to note that on our localhost, when conducting transactions with an external connector, we receive a message confirming the successful completion of the transaction.

Regarding the values for the special variables, we have configured them as follows:

* MY_EDC_FQDN :  the connector itself without any path and redirect to the SERVLET EDC-default
(11001)
* MY_EDC_IDS_BASE_URL:  the connector itself with the path "api/v1/ids/" that redirect to the SERVLET EDC-protocol
(11003)
* EDC_UI_CATALOG_URLS the connector itself with the path "/api/v1/ids/data" that redirect to the SERVLET EDC-protocol
(11003)
Version of the connector: 3.3.0.

Please let us know if these configurations require any adjustments or if there are any additional settings we should consider to resolve the issue.

## Why Is the Feature Desired?

Be able to make contracts to transfer data on PRO.

## Stakeholders

Guido Gehlen.

**Comment by richardtreier** [comment] 2023-06-15 11:25
Hi,

our EDC Community Edition Connectors are pre-configured, with variables such as MY_EDC_FQDN being used to populate other required Core EDC Extension Configurations (this is our file `connector/.env`).

In our recommended deployment a productive EDC requires a reverse proxy in front of it that merge the ports 11002 and 11003 and UI.

That means that the EDC should be able to reach itself and be reachable for other EDCs under the same host.

E.g. with  `MY_EDC_FQDN=my-connector.example.com`
UI should be available under the base path: e.g. `https://my-connector.example.com/assets/config/app-config.json`, and should be secured
The protocol endpoint should be reachable under `https://my-connector.example.com/api/v1/ids/data`, unsecured
The management endpoint should be reachable under  `https://my-connnector.example.com/api/v1/management`, and should be secured

Unfortunately due to limitations of the Core EDC API Group Concept each API Group must have its own port. Combined with different deployment environments using different Reverse Proxies, we do not have an example configuration for that.

We will soon add a more detailed deployment guide to make this more clear.

**Comment by dcarmen1** [comment] 2023-06-21 08:30
Thanks for the support, I have followed the instructions, nevertheless, I’m still having problems to do the contract negotiation.
 
If you could provide more information, I would appreciate it.

**Comment by richardtreier** [comment] 2023-06-21 11:18
We will soon overhaul our deployment documentation and will include better defaults for environment variables, which will hopefully allow our docker compose to be closer to the actual deployment in a productive environment.

See https://github.com/sovity/edc-extensions/issues/390

Until then, to help, I would need more exact details of what doesn't work, a screenshot of the connector's properties on the dashboard page, stack traces, etc.

**Comment by dcarmen1** [comment] 2023-06-23 10:21
We are currently encountering challenges during our negotiation process with an external connector.

![image](https://github.com/sovity/edc-extensions/assets/128583413/47378a8c-cc9b-44eb-bd93-209c454c65ba)

During the contract negotiation process, the system enters a loop, causing the status to remain stuck at "REQUESTED" instead of transitioning to "COMPLETED". As a result, no contract is generated.

Same result when is create it in the REST API:
![image](https://github.com/sovity/edc-extensions/assets/128583413/58e30b88-98f9-4ad9-bc0e-8f954663f053)

Based on the logs, it appears that everything is functioning correctly.
<img width="812" alt="image" src="https://github.com/sovity/edc-extensions/assets/128583413/550e5602-e44d-4b8f-b71b-7edde27f3025">

Here is the configuration for the environment variables:
Connector configuration:
          - name: MY_EDC_FQDN
              value: my-connector.example.com
            - name: MY_EDC_BASE_PATH
              value:
            - name: MY_EDC_PROTOCOL
              value: https://
            - name: WEB_HTTP_PATH
              value: /api
            - name: WEB_HTTP_MANAGEMENT_PATH
              value: /api/v1/management
            - name: WEB_HTTP_PROTOCOL_PATH
              value: /api/v1/ids
            - name: WEB_HTTP_CONTROL_PATH
              value: /api/v1/control
           - name: EDC_HOSTNAME
              value: my-connector.example.com
            - name: EDC_UI_CONNECTOR_ID
              value: https:my-connector.example.com
            - name: MY_EDC_IDS_BASE_URL
              value: https:my-connector.example.com
            - name: IDS_WEBHOOK_ADDRESS
              value: https:my-connector.example.com
            - name: EDC_IDS_ENDPOINT
              value: http:my-connector.example.com/api/v1/ids

Interface configuration:
            - name:  EDC_UI_ACTIVE_PROFILE
              value: mds-open-source
            - name:  EDC_UI_CONFIG_URL
              value: edc-ui-config
            - name: EDC_UI_DATA_MANAGEMENT_API_URL
              value: https:my-connector.example.com/api/v1/management
             - name: EDC_UI_CATALOG_URLS
              value: http://localhost:11003/api/v1/ids/data


If you require any further information, please let us know. We would be happy to provide any additional details you may need.

**Comment by richardtreier** [comment] 2023-06-26 06:40
Hi, there are several hints to what might be going on.

1. For the connector configuration only MY_EDC_FQDN should be set. The other above mentioned env variables will be generated from it on startup, when using our MDS EDC images. See [connector/.env](https://github.com/sovity/edc-extensions/blob/main/connector/.env#L45-L50). 
2. I hope values such as "https:my-connector.example.com" with the invalid protocol are not actually set, but just a copy paste mistake.
3. "my-connector.example.com" hints that the connector is not actually deployed in a way that is reachable from the internet.
4. The same for the fact that the UI Configuration is still referencing some localhost:11003 URL.

Any productive EDC deployment needs to be fully reachable from the internet via it's configured MY_EDC_FQDN (fully-qualified domain name). It also needs a reverse proxy up front that merges the ports.

The transfer process is in the status "Requesting", because your asked the other connector to start a transfer process, but the other connector even reach your connector under the URL `http:my-connector.example.com/api/v1/ids` to start the next process.

EDC Connectors talk to each other asynchronously, that's why they need to be reachable to each other via the host names they themselves know they are deployed under.

**Comment by dcarmen1** [comment] 2023-06-27 14:38
Thank you for providing additional information. Based on the updated details, we’ve made some changes to the configuration to address the issues. Currently, the system is set up as follows:
1.	The UI can be accessed securely via HTTPS using the URL https://mds-ui-url/. This ensures encrypted communication between the client and the UI.
2.	The EDC connector is accessible at https://my-connector.example.com/api/v1/management. To enable secure communication, we have set up a K8s Ingress controller that routes traffic to the connector based on the path /api/v1/ids/data. The traffic reaching the connector is decrypted, and it listens on port 11002 within the connector pod.
3.	Additionally, we have configured another endpoint for the EDC connector at https://my-connector.example.com/api/v1/ids. Similar to the management endpoint, this traffic is routed through the K8s Ingress controller, decrypted, and based on the path /api/v1/ids, and it uses port 11003 within the connector.
With these configurations in place, everything is functioning properly when using both HTTP and HTTPS. However, we encountered an issue specifically when attempting to configure HTTPS for the EDC-protocol connector. We would like to understand why the connector is unable to handle HTTPS traffic in this scenario.

By providing this information, we can further investigate the specific reasons behind the issue with the EDC-protocol connector's inability to handle HTTPS traffic

**Comment by richardtreier** [comment] 2023-06-28 07:49
Hi,

I talked to our infrastructure team and they have several theories regarding the HTTPS/TLS issue:
- If the HTTP port is closed or there are HTTP to HTTPS redirects, we had instances in the past, where that caused credentials to be stripped of (arguably bad) requests, but this caused contract negotiations to fail. 
- We also had instances where the Core EDC's loopback requests onto itself did not respect the protocol and used http:// instead of https://.
- Meaning, the Core EDC might require for HTTP traffic to get through, for contract negotiation to work, for weird edge cases where it loops back on itself. It is quite possible that this is still an issue today as these were issues caused by the Core EDC's underlying Jetty Server and OkHttp, not the Core EDC itself.
- With configuration properties such as the IDS_WEBHOOK_ADDRESS and the EDC_IDS_ENDPOINT containing https:// by default, other EDCs will respect the protocol and request via HTTPS. 

Allowing the pass-through of HTTP traffic is questionable, but might be required as of now.

**Comment by dcarmen1** [comment] 2023-06-30 06:54
Hi! 

Thank you once again for your valuable support! 

Regarding the issue you mentioned, do you happen to know when it is expected to be resolved? It's important for us to address this matter as we can no longer continue operating with HTTP.

**Comment by richardtreier** [comment] 2023-06-30 09:10
Hi,

I understand how this issue can be a blocker depending on your deployment / security policies.

Unfortunately, this is an issue we can only properly validate and re-address, once we have finished #391 and #387. This might take until the middle of August.

**Comment by richardtreier** [comment] 2023-07-06 14:11
Merged with #387

**Closed by richardtreier** 2023-07-06 14:11 UTC
Labels: kind/question, task/analyze

**Comment by richardtreier** [comment] 2024-05-21 07:33
> Hi,
> 
> I talked to our infrastructure team and they have several theories regarding the HTTPS/TLS issue:
> 
>     * If the HTTP port is closed or there are HTTP to HTTPS redirects, we had instances in the past, where that caused credentials to be stripped of (arguably bad) requests, but this caused contract negotiations to fail.
> 
>     * We also had instances where the Core EDC's loopback requests onto itself did not respect the protocol and used `http://` instead of `https://`. So if `http://` traffic was completely blocked, this would also cause contract negotiations to fail.
> 
>     * Meaning, the Core EDC might require for HTTP traffic to get through, for contract negotiation to work, for weird edge cases where it loops back on itself. It is quite possible that this is still an issue today as these were issues caused by the Core EDC's underlying Jetty Server and OkHttp, not the Core EDC itself.
> 
>     * With configuration properties such as the IDS_WEBHOOK_ADDRESS and the EDC_IDS_ENDPOINT containing https:// by default, other EDCs will respect the protocol and request via HTTPS.
> 
> 
> Allowing the pass-through of HTTP traffic is questionable, but might be required as of now.

This should not be the case in current versions of the sovity EDC Community Edition anymore, as they base on newer `>0.2.1` versions of the Eclipse EDC.
